// PrivatePass contract tests
//
// These tests verify the contract behaviour using the Compact runtime.
// They run against the compiled output in managed/ (run `npm run compile` first).
//
// Tests cover:
//   1. Valid credential → proof succeeds, verifiedCount increments
//   2. Invalid credential → proof/assertion fails, counter unchanged
//   3. Multiple verifications → counter accumulates correctly
//   4. Privacy: the private credential does not appear in public ledger state

import { describe, it, expect, beforeEach } from "vitest";

// The compiled contract artifacts are generated by:
//   compact compile src/privatepass.compact managed/
//
// We import the contract module and witnesses type from managed/.
// These paths will exist after compilation.
import type { Contract, Witnesses } from "../managed/privatepass/index.cjs";

// ---------------------------------------------------------------------------
// Test helpers
// ---------------------------------------------------------------------------

// A valid credential: first byte is non-zero (0x01).
// Padded to 32 bytes.
function validCredential(): Uint8Array {
  const cred = new Uint8Array(32);
  cred[0] = 0x01;
  return cred;
}

// An invalid credential: first byte is zero (0x00).
// The circuit's is_valid() check will reject this.
function invalidCredential(): Uint8Array {
  const cred = new Uint8Array(32);
  cred[0] = 0x00; // zero — invalid per our rule
  return cred;
}

// A distinctive valid credential for uniqueness tests.
function anotherValidCredential(): Uint8Array {
  const cred = new Uint8Array(32);
  cred[0] = 0xff;
  cred[1] = 0xab;
  return cred;
}

// ---------------------------------------------------------------------------
// Test suite
// ---------------------------------------------------------------------------

describe("PrivatePass contract", () => {
  let contract: Contract<Witnesses>;
  let ledger: { verifiedCount: bigint };

  // Import the compiled contract module before each test.
  // The managed/ directory is created by: compact compile src/privatepass.compact managed/
  beforeEach(async () => {
    const mod = await import("../managed/privatepass/index.cjs");
    contract = new mod.Contract(mod.ledger.ledger);
    ledger = contract.state;
  });

  // -------------------------------------------------------------------------
  // Test 1: initial state
  // -------------------------------------------------------------------------
  it("starts with verifiedCount of 0", () => {
    expect(ledger.verifiedCount).toBe(0n);
  });

  // -------------------------------------------------------------------------
  // Test 2: valid credential succeeds and increments the counter
  // -------------------------------------------------------------------------
  it("increments verifiedCount when a valid credential is provided", async () => {
    const credential = validCredential();

    // Call the verify() circuit with a witness that returns our credential.
    await contract.circuits.verify(
      {
        // The witness provides the private credential off-chain.
        // It never appears in the proof or on the ledger.
        getCredential: () => credential,
      },
      []
    );

    expect(ledger.verifiedCount).toBe(1n);
  });

  // -------------------------------------------------------------------------
  // Test 3: invalid credential is rejected — counter stays unchanged
  // -------------------------------------------------------------------------
  it("rejects an invalid credential and leaves verifiedCount unchanged", async () => {
    const credential = invalidCredential();

    await expect(
      contract.circuits.verify(
        {
          getCredential: () => credential,
        },
        []
      )
    ).rejects.toThrow(); // The assert() in the circuit causes the call to fail

    // The counter must not have changed.
    expect(ledger.verifiedCount).toBe(0n);
  });

  // -------------------------------------------------------------------------
  // Test 4: multiple valid verifications accumulate correctly
  // -------------------------------------------------------------------------
  it("accumulates verifiedCount across multiple successful verifications", async () => {
    const witnesses = { getCredential: () => validCredential() };

    await contract.circuits.verify(witnesses, []);
    await contract.circuits.verify(witnesses, []);
    await contract.circuits.verify(witnesses, []);

    expect(ledger.verifiedCount).toBe(3n);
  });

  // -------------------------------------------------------------------------
  // Test 5: different valid credentials both succeed
  // -------------------------------------------------------------------------
  it("accepts different valid credentials independently", async () => {
    await contract.circuits.verify({ getCredential: () => validCredential() }, []);
    await contract.circuits.verify({ getCredential: () => anotherValidCredential() }, []);

    expect(ledger.verifiedCount).toBe(2n);
  });

  // -------------------------------------------------------------------------
  // Test 6: privacy — the credential does not appear in ledger state
  // -------------------------------------------------------------------------
  it("does not expose the private credential in public ledger state", async () => {
    const secretCredential = validCredential();
    secretCredential[1] = 0xde;
    secretCredential[2] = 0xad;
    secretCredential[3] = 0xbe;
    secretCredential[4] = 0xef;

    await contract.circuits.verify({ getCredential: () => secretCredential }, []);

    // Inspect the full ledger state — it should only contain verifiedCount.
    const ledgerKeys = Object.keys(ledger);
    expect(ledgerKeys).toEqual(["verifiedCount"]);

    // The credential bytes must not appear anywhere in the stringified state.
    const ledgerString = JSON.stringify(ledger);
    expect(ledgerString).not.toContain("deadbeef");
    expect(ledgerString).not.toContain("de");
  });
});
