// PrivatePass contract tests
//
// These tests verify the contract behaviour using the Compact runtime.
// They run against the compiled output in managed/ (generated by `compact compile src/privatepass.compact managed/`).
//
// Tests cover:
//   1. Initial state: verifiedCount starts at 0
//   2. Valid credential: proof succeeds and verifiedCount increments
//   3. Invalid credential: proof/assertion fails and counter remains unchanged
//   4. Multiple verifications: counter accumulates monotonically
//   5. Distinct valid credentials: accepted independently
//   6. Privacy: private credential bytes never leak into public ledger state

import { describe, it, expect, beforeEach } from "vitest";
import {
  createConstructorContext,
  createCircuitContext,
  dummyContractAddress,
} from "@midnight-ntwrk/compact-runtime";
import {
  Contract,
  ledger,
  type Witnesses,
  type Ledger,
} from "../managed/contract/index.js";

// ---------------------------------------------------------------------------
// Test helpers
// ---------------------------------------------------------------------------

function validCredential(): Uint8Array {
  const cred = new Uint8Array(32);
  cred[0] = 0x01; // non-zero first byte = valid
  return cred;
}

function invalidCredential(): Uint8Array {
  const cred = new Uint8Array(32);
  cred[0] = 0x00; // zero first byte = invalid
  return cred;
}

function anotherValidCredential(): Uint8Array {
  const cred = new Uint8Array(32);
  cred[0] = 0xff;
  cred[1] = 0xab;
  return cred;
}

// ---------------------------------------------------------------------------
// Test suite
// ---------------------------------------------------------------------------

describe("PrivatePass contract", () => {
  const coinPublicKey = { bytes: new Uint8Array(32) };
  const contractAddress = dummyContractAddress();

  let currentLedgerState: any;

  // Initialize fresh contract state before each test
  beforeEach(async () => {
    const dummyWitnesses: Witnesses<any> = {
      getCredential: () => [{}, validCredential()],
    };
    const contract = new Contract(dummyWitnesses);
    const ctorContext = createConstructorContext({}, coinPublicKey);
    const { currentContractState } = await contract.initialState(ctorContext);
    currentLedgerState = currentContractState.data;
  });

  // Helper to execute verify circuit with specific credential witness
  async function executeVerify(credential: Uint8Array): Promise<Ledger> {
    const witnesses: Witnesses<any> = {
      getCredential: () => [{}, credential],
    };
    const contract = new Contract(witnesses);
    const circuitContext = createCircuitContext(
      "verify",
      contractAddress,
      coinPublicKey,
      currentLedgerState,
      {}
    );

    const { context } = await contract.circuits.verify(circuitContext);
    currentLedgerState = context.callContext.currentQueryContext.state.state;
    return ledger(currentLedgerState);
  }

  // -------------------------------------------------------------------------
  // Test 1: initial state
  // -------------------------------------------------------------------------
  it("starts with verifiedCount of 0", () => {
    const current = ledger(currentLedgerState);
    expect(current.verifiedCount).toBe(0n);
  });

  // -------------------------------------------------------------------------
  // Test 2: valid credential succeeds and increments the counter
  // -------------------------------------------------------------------------
  it("increments verifiedCount when a valid credential is provided", async () => {
    const current = await executeVerify(validCredential());
    expect(current.verifiedCount).toBe(1n);
  });

  // -------------------------------------------------------------------------
  // Test 3: invalid credential is rejected — counter stays unchanged
  // -------------------------------------------------------------------------
  it("rejects an invalid credential and leaves verifiedCount unchanged", async () => {
    await expect(executeVerify(invalidCredential())).rejects.toThrow();

    // The counter must not have changed
    const current = ledger(currentLedgerState);
    expect(current.verifiedCount).toBe(0n);
  });

  // -------------------------------------------------------------------------
  // Test 4: multiple valid verifications accumulate correctly
  // -------------------------------------------------------------------------
  it("accumulates verifiedCount across multiple successful verifications", async () => {
    await executeVerify(validCredential());
    await executeVerify(validCredential());
    const current = await executeVerify(validCredential());

    expect(current.verifiedCount).toBe(3n);
  });

  // -------------------------------------------------------------------------
  // Test 5: different valid credentials both succeed
  // -------------------------------------------------------------------------
  it("accepts different valid credentials independently", async () => {
    await executeVerify(validCredential());
    const current = await executeVerify(anotherValidCredential());

    expect(current.verifiedCount).toBe(2n);
  });

  // -------------------------------------------------------------------------
  // Test 6: privacy — the credential does not appear in ledger state
  // -------------------------------------------------------------------------
  it("does not expose the private credential in public ledger state", async () => {
    const secretCredential = validCredential();
    secretCredential[1] = 0xde;
    secretCredential[2] = 0xad;
    secretCredential[3] = 0xbe;
    secretCredential[4] = 0xef;

    const current = await executeVerify(secretCredential);

    // Inspect the full ledger state — it must only contain verifiedCount
    const ledgerKeys = Object.keys(current);
    expect(ledgerKeys).toEqual(["verifiedCount"]);

    // The secret credential bytes must not appear anywhere in the ledger state
    const ledgerString = JSON.stringify(current, (_k, v) =>
      typeof v === "bigint" ? v.toString() : v
    );
    expect(ledgerString).not.toContain("deadbeef");
    expect(ledgerString).not.toContain("de");
  });
});
